#!/bin/sh
# https://github.com/wikimedia/mediawiki-extensions-Disambiguator/archive/REL1_24.zip
# mediawiki-extensions-Disambiguator-REL1_24

#BASESITE="https://github.com/wikimedia/mediawiki-extensions-"
#BASESITE="https://codeload.github.com/eckserah/mediawiki-extensions-"
function get_file(){
	local url="$1"
	local outputFile="$2"
	local success=0
	wget -q "$url" -O "$outputFile"
	if [ $? -ne 0 ]; then
		echo "ERROR: Failed to download from $URL!"
		success=3
	fi
	return "$success"
}

function get_gerrit() {
	local basesite="https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/$BASETYPE/$EXTNAME"
	local COMMITURL="$basesite/+/refs/tags/REL$EXTVERSION"
	ARCHCOMMIT=$(curl $COMMITURL | grep -oP '(?<=commit</th><td>).*(?=</td><td><span>\[<a href)')
	if [ -z "$ARCHCOMMIT" ]; then
		echo "ERROR: Unable to get commit from gerrit url ($COMMITURL) for tag REL$EXTVERSION"
		return 6
	fi
	URL="$basesite/+archive/$ARCHCOMMIT.tar.gz"
	OUTPUTFILE="$EXTNAME.tar.gz"
	get_file "$URL" "$OUTPUTFILE"
	return $?
}

EXTNAME="$1"
EXTVERSION="$2"
EXTSKINS="$3"
BASETYPE="skins"

if [ -z "$EXTNAME" ]; then
	echo "ERROR: Missing required extension name..."
	exit -1
fi

if [ -z "$EXTVERSION" ]; then
	echo "ERROR: Missing required extension version..."
	exit -2
fi

if [ -z "$EXTSKINS" ]; then
	BASETYPE="extensions"
fi

OLDPATH="mediawiki-$BASETYPE-$EXTNAME-REL$EXTVERSION"

BASESITE="https://codeload.github.com/wikimedia/mediawiki-$BASETYPE-"
URL="$BASESITE$EXTNAME/zip/refs/heads/REL$EXTVERSION"

OUTPUTFILE="$EXTNAME.zip"

echo "Attempting to download MediaWiki $BASETYPE $EXTNAME v$EXTVERSION..."

get_file "$URL" "$OUTPUTFILE"

if [ $? -ne 0 ]; then
	get_gerrit
	if [ $? -ne 0 ]; then
		exit $?
	fi
fi

UNZIPTYPE="unzip"

if [[ "${URL: -3}" != ".gz" ]]; then
	unzip -o -q "$OUTPUTFILE"
else
	mkdir -p "./mediawiki-$BASETYPE-$EXTNAME-REL$EXTVERSION"
	tar -xzf "$OUTPUTFILE" -C "./mediawiki-$BASETYPE-$EXTNAME-REL$EXTVERSION"
	UNZIPTYPE="untar"
fi

if [ $? -ne 0 ]; then
	echo "ERROR: Failed to $UNZIPTYPE $OUTPUTFILE!"
	exit -4
fi

NEWPATH="$EXTNAME"
rm -rf "$NEWPATH"
mv -f "$OLDPATH" "$NEWPATH"

if [ $? -ne 0 ]; then
	echo "ERROR: Failed to move output directory $OLDPATH!"
	exit -5
fi

echo "Successfully uncompressed MediaWiki $BASETYPE to $NEWPATH..."