#!/bin/bash

IP=/home/uesp/www/w
RJ=$IP/maintenance/runJobs.php
LANG="en"

pushd $IP

while true; do
		# Job types that need to be run ASAP mo matter how many of them are in the queue
		# Those jobs should be very "cheap" to run
	php74 $RJ --memory-limit=max --uesplang=$LANG --maxjobs=1000
	sleep 1
done

popd
