#!/bin/bash

IP=/home/uesp/dev/www/w
RJ=$IP/maintenance/runJobs.php

pushd $IP

echo Starting dev job service...
# Wait a minute after the server starts up to give other processes time to get started
sleep 6
echo Started.

while true; do
		# Job types that need to be run ASAP mo matter how many of them are in the queue
		# Those jobs should be very "cheap" to run
	php71 $RJ --type="enotifNotify" --server=https://dev.uesp.net
	sleep 1
	php71 $RJ --type="htmlCacheUpdate" --maxjobs=50 --server=https://dev.uesp.net
	sleep 1
	
		# Everything else, limit the number of jobs on each batch
		# The --wait parameter will pause the execution here until new jobs are added,
		# to avoid running the loop without anything to do
	php71 $RJ --wait --maxjobs=10 --server=https://dev.uesp.net
	
		# Wait some seconds to let the CPU do other things, like handling web requests, etc
	echo Waiting for 15 seconds...
	sleep 15
done

popd